spring:
  application:
    name: api-gateway

server:
  port: 5555

zuul:
  ignored-services: '*'
  routes:
    common-function: /helloServer/**
    feign-consumer: /feignConsumer/**
    api-a:
      path: /api-a/**
      url: forward:/local
#    hello-server:
#      path: /helloServer/**
#      serviceId: common-function
#    feign-server:
#      path: /feign/**
#      serviceId: feign-consumer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka